[project]
name = "helloworld"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.1.5",
]

[dependency-groups]
dev = [
    "black>=25.1.0",
    "pytest>=8.3.4",
    "pytest-django>=4.9.0",
]
