name: Build Django App

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install the latest version of uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          version: latest
      - name: Install dependencies
        run: uv sync --locked

      - name: Test with python
        run: uv run pytest

      - name: Run Black
        run: uv run black . --check

      - name: Collect static files
        run: uv run python manage.py collectstatic --noinput

      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          curl -X POST -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          -H "Accept: application/json" \
          -H "Content-Type: application/json" \
          -d '{"serviceId": "${{ vars.RENDER_SERVICE_ID }}"}' \
          https://api.render.com/v1/services/${{ vars.RENDER_SERVICE_ID }}/deploys