name: Deploy Django App to Render

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build Django App"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Wait for Approval
      uses: hmarr/auto-approve-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Deploy to Render
      env:
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
      run: |
        curl -X POST -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
        -H "Accept: application/json" \
        -H "Content-Type: application/json" \
        -d '{"serviceId": "${{ vars.RENDER_SERVICE_ID }}"}' \
        https://api.render.com/v1/services/${{ vars.RENDER_SERVICE_ID }}/deploys