name: Django CI/CD to PythonAnywhere

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install the latest version of uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          version: latest
      - name: Install dependencies
        run: uv sync --locked

      - name: Collect static files
        run: uv run python manage.py collectstatic

      - name: Test with python
        run: uv run pytest

      - name: Run Black
        run: uv run black . --check


#