name: Django CI/CD to PythonAnywhere

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.9', '3.10', '3.11', '3.12', '3.13' ] # Test with multiple Python versions

    steps:
      - uses: actions/checkout@v4
      - name: Install the latest version of uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: uv sync --locked

      - name: Test with python ${{ matrix.python-version }}
        run: uv run --frozen pytest

      - name: Run Black
        run: uv run black . --check


#